Update zh-cn
melontini/andromeda-wiki pull request #43
Opened 2024-05-14 06:32 UTC by Rad586

2024-05-14 16:11 UTC, melontini requested changes

2024-05-14 16:11 UTC, melontini commented on docs/zh-cn/misc.md
> +With the new config system introduced in 1.12.0, Andromeda gained support for Commander expressions right in the config. In most cases only `game` configs support expressions.
Missed a line

2024-05-15 09:10 UTC, Rad586 commented on docs/zh-cn/misc.md
> +With the new config system introduced in 1.12.0, Andromeda gained support for Commander expressions right in the config. In most cases only `game` configs support expressions.
fixed🗿

2024-05-15 13:58 UTC, melontini approved these changes

2024-05-15 13:58 UTC, merged